### ISSUE TITLE
about bwa-mem find_circ programes

### ISSUE THREAD

**Issue by smm19900210** [marvin-jens/find_circ#8]
i have a question, what's the different of find_circ and bwa-mem_find_circ programes?

**Comment by smm19900210** [comment]
it means i can use bwa-mem

**Comment by mschilli87** [comment]
Note that the main repository for this (the `bowtie2` based) version of `find_circ` is now at  https://github.com/rajewsky-lab/find_circ. It is, however, not any longer the recommended version. Instead, the (`bwa-mem` based) version at  https://github.com/rajewsky-lab/find_circ2 should be considered.
